from pydantic import BaseModel
from typing import List, Optional

class KPIAnalyzeResponse(BaseModel):
    success: bool
    domain: Optional[str] = None
    suggested_areas: List[str] = []
    message: str

class KPIGenerateRequest(BaseModel):
    domain: str
    area: str
    catalog: str # To locate the correct state
    schema_name: str

class KPIGenerateResponse(BaseModel):
    success: bool
    kpis: str  # The raw DAX string generated by the agent
    message: str